import { useEffect, useState } from 'react';
import { getEvidence, getStatistics } from '../services/api';

export default function Analytics() {
	const [stats, setStats] = useState(null); const [evidence, setEvidence] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
	const load = async () => { setLoading(true); setError(null); try { const [statistics, evidenceData] = await Promise.all([getStatistics(), getEvidence()]); setStats(statistics); setEvidence(Array.isArray(evidenceData) ? evidenceData : evidenceData?.items || []); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } };
	useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, []);
	const values = stats ? [['Active cameras', stats.active_cameras ?? stats.activeCameras], ['People detected', stats.people_detected ?? stats.peopleDetected], ['Vehicles detected', stats.vehicles_detected ?? stats.vehiclesDetected], ['High-risk events', stats.high_risk_events ?? stats.highRiskEvents]] : [];
	return <div className="p-6"><div className="mb-6"><h1 className="text-2xl font-bold">Analytics</h1><p className="text-gray-500">Detection statistics and evidence</p></div>{error && <div className="mb-4 rounded border border-red-200 bg-red-50 p-4 text-red-700">{error} <button onClick={load} className="ml-3 underline">Retry</button></div>}{loading ? <div className="rounded bg-white p-8 text-center text-gray-500">Loading analytics...</div> : <><div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([label, value]) => <div key={label} className="rounded-lg bg-white p-5 shadow"><div className="text-2xl font-bold">{value ?? 0}</div><div className="text-sm text-gray-500">{label}</div></div>)}</div><h2 className="mb-3 text-xl font-bold">Evidence</h2><div className="grid grid-cols-1 gap-4 md:grid-cols-3">{evidence.map((item) => <a key={item.id} href={item.snapshot_url} target="_blank" rel="noreferrer" className="rounded-lg bg-white p-4 shadow"><div className="font-semibold">{item.event_type || 'Detection'}</div><div className="text-sm text-gray-500">Camera {item.camera_id} · Track {item.track_id || 'N/A'}</div></a>)}{!evidence.length && <div className="text-gray-500">No evidence available.</div>}</div></>}</div>;
}
