import { useCallback, useEffect, useState } from 'react';
import { getEvents } from '../services/api';

export default function Events() {
  const [events, setEvents] = useState([]); const [type, setType] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const pageSize = 10;
  const loadEvents = useCallback(async () => { setLoading(true); setError(null); try { const result = await getEvents(type ? { type } : undefined); setEvents(Array.isArray(result) ? result : result?.items || []); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } }, [type]);
  useEffect(() => { const timer = setTimeout(loadEvents, 0); return () => clearTimeout(timer); }, [loadEvents]);
  const visible = events.slice((page - 1) * pageSize, page * pageSize); const pages = Math.max(1, Math.ceil(events.length / pageSize));
  return <div className="p-6"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Events</h1><p className="text-gray-500">Recorded detections and security events</p></div><input value={type} onChange={(event) => { setType(event.target.value); setPage(1); }} placeholder="Filter by type" className="rounded border px-3 py-2" /></div>{error && <div className="mb-4 rounded border border-red-200 bg-red-50 p-4 text-red-700">{error} <button onClick={loadEvents} className="ml-3 underline">Retry</button></div>}<div className="overflow-x-auto rounded-lg bg-white shadow">{loading ? <div className="p-8 text-center text-gray-500">Loading events...</div> : <table className="w-full text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Time</th><th className="p-3">Camera</th><th className="p-3">Type</th><th className="p-3">Object</th><th className="p-3">Track</th><th className="p-3">Risk</th></tr></thead><tbody>{visible.map((event) => <tr key={event.id} className="border-b"><td className="p-3">{event.timestamp ? new Date(event.timestamp).toLocaleString() : '-'}</td><td className="p-3">{event.camera_name || '-'}</td><td className="p-3">{event.type || '-'}</td><td className="p-3">{event.object_type || '-'}</td><td className="p-3">{event.track_id || '-'}</td><td className="p-3">{event.risk || '-'}</td></tr>)}</tbody></table>}{!loading && !visible.length && <div className="p-8 text-center text-gray-500">No events found.</div>}</div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-gray-500">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1 disabled:opacity-50">Previous</button><button disabled={page === pages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1 disabled:opacity-50">Next</button></div></div></div>;
}// TODO: Implement event logs with filters.
